version: "3.8"

services:
  hazelcast:
    image: hazelcast/hazelcast:4.0.1
    ports:
      - "5701:5701"

  dynamodb-local:
    command: "-jar DynamoDBLocal.jar -sharedDb -optimizeDbBeforeStartup -dbPath ./data"
    image: "amazon/dynamodb-local:latest"
    container_name: dynamodb-local
    ports:
      - "8000:8000"
    volumes:
      - "./docker/dynamodb:/home/dynamodblocal/data"
    working_dir: /home/dynamodblocal

  management-center:
    image: hazelcast/management-center:4.0.3
    environment:
      - MC_INIT_CMD=./mc-conf.sh cluster add -H=/data -ma hazelcast:5701 -cn dev
    ports:
      - 8080:8080
